# Generated by Django 5.1.3 on 2024-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arrsite", "0001_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="tags",
            field=models.CharField(
                choices=[
                    ("important", "Важное"),
                    ("news", "Новости"),
                    ("update", "Обновление"),
                    ("event", "Мероприятие"),
                ],
                default="news",
                max_length=20,
            ),
        ),
    ]
