# Generated by Django 4.2.16 on 2024-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_iin', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('head_fullname', models.CharField(max_length=255)),
                ('is_ndspayer', models.BooleanField(default=False)),
                ('tax_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('has_licenses', models.BooleanField(default=False)),
                ('licenses_quantity', models.IntegerField(default=0)),
                ('reliability_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financial_activity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_presence', models.IntegerField()),
                ('business_stability', models.IntegerField()),
                ('company_age', models.IntegerField()),
                ('registration_history', models.JSONField(default=dict)),
                ('financial_data', models.JSONField(default=dict)),
                ('contact_info', models.JSONField(default=dict)),
                ('analytics_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Данные компании',
                'verbose_name_plural': 'Данные компаний',
            },
        ),
    ]
