# Generated by Django 4.2.16 on 2024-11-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrsite', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='arrsite.notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='arrsite.companydata'),
        ),
    ]
