# Generated by Django 4.2.16 on 2024-11-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrsite', '0004_notification_is_global_notification_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reply_type',
            field=models.CharField(blank=True, choices=[('comment', 'Комментарий'), ('completed', 'Исполнено'), ('rejected', 'Не исполнено')], max_length=10, null=True),
        ),
    ]
